server:
  port: 8080

# 配置了也没用，config了new了一个pikachu
pokemon:
  pikachu:
    name: pika
    height: 63
    girl-friend:
      name: unused
      interest: hiking
    enabled: true
logging:
  level:
    root: debug
